name: 自动删除旧的工作流
on:
  #定时触发开始编译(把下面两个#去掉开启,时间设置请看定时编译说明)
  schedule:
    - cron: 0 10 * * 4

  workflow_dispatch:
    inputs:
      delete-older-workflow:
        description: '自动删除旧的工作流'
        required: false
        default: 'true'           #自动删除旧的工作流（true=开启）（false=关闭）
      rele:
        description: '保留[X]个Releases不被删除(可改)'
        required: true
        default: '0'

jobs:
  del_runs:
    runs-on: Ubuntu-20.04
    name: delete-workflow-runs
    steps:
    
      - name: 自动删除旧的工作流
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ env.retain_days }}
          keep_minimum_runs: 0
